python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv  \
  --model_id Traffic_96_96 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 862  \
  --dec_in 862  \
  --c_in 862  \
  --c_out 862  \
  --d_model 512 \
  --itr 1 \
  --train_epochs 150 \
  --batch_size 8 \
  --patience 20 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 8 \
  --stride 24 \
  --e_layers 1 \
  --local_and_global_adaptive_level 10 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 10 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv  \
  --model_id Traffic_96_192 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --enc_in 862  \
  --dec_in 862  \
  --c_in 862  \
  --c_out 862  \
  --d_model 256 \
  --itr 1 \
  --train_epochs 150 \
  --batch_size 8 \
  --patience 20 \
  --learning_rate 0.0002 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 4 \
  --stride 29 \
  --e_layers 1 \
  --local_and_global_adaptive_level 12 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 12 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv  \
  --model_id Traffic_96_336 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --enc_in 862  \
  --dec_in 862  \
  --c_in 862  \
  --c_out 862  \
  --d_model 512 \
  --itr 1 \
  --train_epochs 150 \
  --batch_size 8 \
  --patience 20 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 5 \
  --stride 28 \
  --e_layers 2 \
  --local_and_global_adaptive_level 5 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 5 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv  \
  --model_id Traffic_96_720 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --enc_in 862  \
  --dec_in 862  \
  --c_in 862  \
  --c_out 862  \
  --d_model 384 \
  --itr 1 \
  --train_epochs 150 \
  --batch_size 8 \
  --patience 20 \
  --learning_rate 0.00008 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 5 \
  --stride 33 \
  --e_layers 2 \
  --local_and_global_adaptive_level 10 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 10 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0

