python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_96 \
  --model FTP \
  --data ETTh2  \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 1024 \
  --itr 1 \
  --train_epochs 30 \
  --batch_size 32 \
  --patience 3 \
  --learning_rate 0.00005 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 4 \
  --stride 10 \
  --e_layers 1 \
  --local_and_global_adaptive_level 12 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 12 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --is_use_adaptive_stride 1


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_192 \
  --model FTP \
  --data ETTh2  \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 376 \
  --itr 1 \
  --train_epochs 30 \
  --batch_size 32 \
  --patience 3 \
  --learning_rate 0.00005 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 1 \
  --stride 1 \
  --e_layers 1 \
  --local_and_global_adaptive_level 35 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 35 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --is_use_adaptive_stride 1


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_336 \
  --model FTP \
  --data ETTh2  \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 10 \
  --batch_size 16 \
  --patience 5 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 1 \
  --stride 29 \
  --e_layers 1 \
  --local_and_global_adaptive_level 2 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 2 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_720 \
  --model FTP \
  --data ETTh2  \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 10 \
  --batch_size 16 \
  --patience 3 \
  --learning_rate 0.00005 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 43 \
  --stride 46 \
  --e_layers 3 \
  --local_and_global_adaptive_level 1 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 1 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0