python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96 \
  --model FTP \
  --data ETTh1  \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 16 \
  --patience 3 \
  --learning_rate 0.00005 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 5 \
  --stride 14 \
  --e_layers 1 \
  --local_and_global_adaptive_level 9 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 9 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_192 \
  --model FTP \
  --data ETTh1  \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 512 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 16 \
  --patience 3 \
  --learning_rate 0.00005 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 1 \
  --stride 30 \
  --e_layers 1 \
  --local_and_global_adaptive_level 28 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 28 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_336 \
  --model FTP \
  --data ETTh1  \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 32 \
  --patience 3 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 3 \
  --stride 10 \
  --e_layers 2 \
  --local_and_global_adaptive_level 15 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 15 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_720 \
  --model FTP \
  --data ETTh1  \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --enc_in 7 \
  --dec_in 7 \
  --c_in 7 \
  --c_out 7 \
  --d_model 512 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 16 \
  --patience 3 \
  --learning_rate 0.00007 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 21 \
  --stride 27 \
  --e_layers 1 \
  --local_and_global_adaptive_level 2 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 2 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0

