python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id Solar_96_96 \
  --model FTP \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 137 \
  --dec_in 137 \
  --c_in 137 \
  --c_out 137 \
  --d_model 1024 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 64 \
  --patience 8 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 6 \
  --stride 12 \
  --e_layers 1 \
  --local_and_global_adaptive_level 3 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 3 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id Solar_96_192 \
  --model FTP \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --enc_in 137 \
  --dec_in 137 \
  --c_in 137 \
  --c_out 137 \
  --d_model 128 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 64 \
  --patience 7 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 3 \
  --stride 5 \
  --e_layers 2 \
  --local_and_global_adaptive_level 20 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 20 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id Solar_96_336 \
  --model FTP \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --enc_in 137 \
  --dec_in 137 \
  --c_in 137 \
  --c_out 137 \
  --d_model 128 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 24 \
  --patience 7 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 7 \
  --stride 1 \
  --e_layers 2 \
  --local_and_global_adaptive_level 11 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 11 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id Solar_96_720 \
  --model FTP \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --enc_in 137 \
  --dec_in 137 \
  --c_in 137 \
  --c_out 137 \
  --d_model 128 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 16 \
  --patience 8 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 3 \
  --stride 18 \
  --e_layers 2 \
  --local_and_global_adaptive_level 11 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 11 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder
