python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_12 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 12 \
  --enc_in 358 \
  --dec_in 358 \
  --c_in 358 \
  --c_out 358 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 32 \
  --patience 8 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 3 \
  --stride 8 \
  --e_layers 3 \
  --local_and_global_adaptive_level 15 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 15 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.1 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_24 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 24 \
  --enc_in 358 \
  --dec_in 358 \
  --c_in 358 \
  --c_out 358 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 32 \
  --patience 8 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 3 \
  --stride 8 \
  --e_layers 3 \
  --local_and_global_adaptive_level 15 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 15 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.1 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_48 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --enc_in 358 \
  --dec_in 358 \
  --c_in 358 \
  --c_out 358 \
  --d_model 384 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 16 \
  --patience 8 \
  --learning_rate 0.00007 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 7 \
  --stride 1 \
  --e_layers 2 \
  --local_and_global_adaptive_level 5 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 5 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_96 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 358 \
  --dec_in 358 \
  --c_in 358 \
  --c_out 358 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 12 \
  --patience 8 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 9 \
  --stride 17 \
  --e_layers 3 \
  --local_and_global_adaptive_level 3 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 3 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder
