python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS07.npz \
  --model_id PEMS07_96_12 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 12 \
  --enc_in 883 \
  --dec_in 883 \
  --c_in 883 \
  --c_out 883 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 60 \
  --batch_size 8 \
  --patience 7 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 5 \
  --stride 7 \
  --e_layers 3 \
  --local_and_global_adaptive_level 10 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 10 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.15 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS07.npz \
  --model_id PEMS07_96_24 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 24 \
  --enc_in 883 \
  --dec_in 883 \
  --c_in 883 \
  --c_out 883 \
  --d_model 192 \
  --itr 1 \
  --train_epochs 60 \
  --batch_size 8 \
  --patience 7 \
  --learning_rate 0.00008 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 3 \
  --stride 9 \
  --e_layers 3 \
  --local_and_global_adaptive_level 12 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 12 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.15 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS07.npz \
  --model_id PEMS07_96_48 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --enc_in 883 \
  --dec_in 883 \
  --c_in 883 \
  --c_out 883 \
  --d_model 384 \
  --itr 1 \
  --train_epochs 60 \
  --batch_size 8 \
  --patience 7 \
  --learning_rate 0.0001 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 15 \
  --stride 10 \
  --e_layers 1 \
  --local_and_global_adaptive_level 6 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 6 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0 \
  --gpu 0 \
  --time_encoder


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS07.npz \
  --model_id PEMS07_96_96 \
  --model FTP \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 883 \
  --dec_in 883 \
  --c_in 883 \
  --c_out 883 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 60 \
  --batch_size 8 \
  --patience 7 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 4 \
  --stride 20 \
  --e_layers 1 \
  --local_and_global_adaptive_level 5 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 5 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.1 \
  --gpu 0 \
  --time_encoder
