python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_96 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --enc_in 321 \
  --dec_in 321 \
  --c_in 321 \
  --c_out 321 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 32 \
  --patience 8 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 4 \
  --stride 8 \
  --e_layers 2 \
  --local_and_global_adaptive_level 8 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 8 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.1 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_192 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --enc_in 321 \
  --dec_in 321 \
  --c_in 321 \
  --c_out 321 \
  --d_model 192 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 32 \
  --patience 8 \
  --learning_rate 0.00006 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 11 \
  --stride 6 \
  --e_layers 2 \
  --local_and_global_adaptive_level 7 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 7 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.15 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_336 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --enc_in 321 \
  --dec_in 321 \
  --c_in 321 \
  --c_out 321 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 24 \
  --patience 8 \
  --learning_rate 0.00015 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 2 \
  --stride 13 \
  --e_layers 2 \
  --local_and_global_adaptive_level 11 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 11 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.15 \
  --gpu 0


python -u run.py \
  --is_training 1 \
  --task_name long_term_forecast \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_720 \
  --model FTP \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --enc_in 321 \
  --dec_in 321 \
  --c_in 321 \
  --c_out 321 \
  --d_model 256 \
  --itr 1 \
  --train_epochs 70 \
  --batch_size 16 \
  --patience 8 \
  --learning_rate 0.00012 \
  --lradj cosine \
  --des 'Exp' \
  --unit_patch_len 6 \
  --stride 11 \
  --e_layers 2 \
  --local_and_global_adaptive_level 14 \
  --local_and_global_parallel_or_serial serial \
  --channel_mix_information_adaptive_level 14 \
  --channel_mix_information_parallel_or_serial serial \
  --dropout 0.1 \
  --gpu 0